DATA_DIR: "/home/johanna/files"
FILE_LIST: "/home/johanna/files/files.txt"


RESULTS_DIR: "./resultsFC/case1_coronaryOnlyValData"
TRAIN_FILE_LIST: "./resultsFC/case1_coronaryOnly_useYc/train.txt"
VAL_FILE_LIST: "./resultsFC/case1_coronaryOnly_useYc/val2.txt"
TEST_FILE_LIST: "./resultsFC/case1_coronaryOnly_useYc/test.txt"
EXPERIMENT_FILE: "I2INetNonLinearTH"
THRESHOLD: 0.3
THRESHOLDTYP: "CONSTANT"

MODEL_DIR: "./resultsFC/case1_coronaryOnly/model"
MODEL_NAME: "I2IFC"

SPACING: 0.035
DIMS: 192
NUM_CONTOUR_POINTS: 30
PATH_START: 2
LOFT: true
LOCAL_MAX_NORM: true
ROTATE: true
RANDOM_CROP: true
NUM_CHANNELS: 1
#maximal offset of random image crop center-->in train_utils.py: random_crop()
PATH_PERTURB: 5
NORMALIZE: LOCAL_MAX_NORM
#if True uses RadiusRanges as vessel size ranges else if False devides the total vessel size range into 15 parts
RADIUSRANGEFIXED: True
RADIUSRANGES: [0.0,0.0957298927,0.1914597854,0.2871896781,0.3829195709,0.4786494636,0.5743793563,0.670109249,0.7658391417,0.8615690344,0.9572989271,1.0530288198,1.1487587126,1.2444886053,1.340218498,1.4359483907,5.0]
#[0.0,0.075,0.1,0.125,0.15,0.175,0.2,0.225,0.25,5]
  #[0.000,0.002,0.003,0.004,0.005,0.006,0.007,0.008,0.009,0.01,0.011,.012,0.013,0.014,5]
DICERANGES: [0.0,0.10,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]
DICESPLIT: 0.3

VAL_PATTERNS:
  - OSMSC0109
  - normal1
  - OSMSC0189

TEST_PATTERNS:
  - cabg11
  - OSMSC0113
  - OSMSC0185

TRAIN_PATTERNS:
  - cabg5
  - OSMSC0108
  - OSMSC0002
  - cabg10
  - normal4
  - OSMSC0115
  - OSMSC0158
  - OSMSC0172
  - OSMSC0173
  - OSMSC0183
  - OSMSC0184
  - OSMSC0186
  - OSMSC0187
  - OSMSC0188
