DATA_DIR: "/home/johanna/files"
FILE_LIST: "/home/johanna/files/files.txt"


RESULTS_DIR: "./results/case1_coronary"
TRAIN_FILE_LIST: "./results/case1_coronary/train.txt"
VAL_FILE_LIST: "./results/case1_coronary/val.txt"
TEST_FILE_LIST: "./results/case1_coronary/test.txt"
EXPERIMENT_FILE: "I2INet"
PRETRAINED_MODEL_PATH: "./results/case1_loft/model/I2I"
THRESHOLD: 0.3

MODEL_DIR: "./results/case1_coronary/model"
MODEL_NAME: "I2IPreTrainedCoronary"

SPACING: 0.035
DIMS: 192
NUM_CONTOUR_POINTS: 30
PATH_START: 2
LOFT: true
LOCAL_MAX_NORM: true
ROTATE: true
RANDOM_CROP: true
NUM_CHANNELS: 1
#maximal offset of random image crop center-->in train_utils.py: random_crop()
PATH_PERTURB: 5
NORMALIZE: LOCAL_MAX_NORM

VAL_PATTERNS:
  - OSMSC0109
  - normal1
  - OSMSC0189

TEST_PATTERNS:
  - cabg11
  - OSMSC0113
  - OSMSC0185

TRAIN_PATTERNS:
  - cabg5
  - OSMSC0108
  - OSMSC0002
  - cabg10
  - normal4
  - OSMSC0115
  - OSMSC0158
  - OSMSC0172
  - OSMSC0173
  - OSMSC0183
  - OSMSC0184
  - OSMSC0186
  - OSMSC0187
  - OSMSC0188
