DATA_DIR: "/home/johanna/files"
FILE_LIST: "/home/johanna/files/files.txt"


RESULTS_DIR: "./resultsFC/case1_coronaryPretrained_useYc"
TRAIN_FILE_LIST: "./resultsFC/case1_coronaryOnly_useYc/train.txt"
VAL_FILE_LIST: "./resultsFC/case1_coronaryOnly_useYc/val.txt"
TEST_FILE_LIST: "./resultsFC/case1_coronaryOnly_useYc/test.txt"
EXPERIMENT_FILE: "I2INet"
PRETRAINED_MODEL_PATH: "./resultsFC/case1_loft_useYc/model/I2IFC"
THRESHOLD: 0.3
THRESHOLDTYP: "CONSTANT"

MODEL_DIR: "./resultsFC/case1_coronaryPretrained_useYc/model"
MODEL_NAME: "I2IFCPretrainedCoronary_useYc"

SPACING: 0.035
DIMS: 192
NUM_CONTOUR_POINTS: 30
PATH_START: 2
LOFT: true
LOCAL_MAX_NORM: true
ROTATE: true
RANDOM_CROP: true
NUM_CHANNELS: 1
#maximal offset of random image crop center-->in train_utils.py: random_crop()
PATH_PERTURB: 5
NORMALIZE: LOCAL_MAX_NORM
RADIUSRANGEFIXED: False
RADIUSRANGES: [0.000,0.002,0.003,0.004,0.005,0.006,0.007,0.008,0.009,0.01,0.011,.012,0.013,0.014,5]
DICERANGES: [0.0,0.10,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]
DICESPLIT: 0.3


VAL_PATTERNS:
  - OSMSC0109
  - normal1
  - OSMSC0189

TEST_PATTERNS:
  - cabg11
  - OSMSC0113
  - OSMSC0185

TRAIN_PATTERNS:
  - cabg5
  - OSMSC0108
  - OSMSC0002
  - cabg10
  - normal4
  - OSMSC0115
  - OSMSC0158
  - OSMSC0172
  - OSMSC0173
  - OSMSC0183
  - OSMSC0184
  - OSMSC0186
  - OSMSC0187
  - OSMSC0188
