CASES_DIR: "./cases"
CASES_PREFIX: "/home/marsdenlab/datasets/vascular_data"

LEAK: 0.2
CROP_DIMS: 128
IMAGE_DIMS: 192
BATCH_SIZE: 16
LEARNING_RATE: 1e-4
TRAIN_STEPS: 20000
PRINT_STEP: 200
INIT: 7e-2
LAM: 1e-3
NUM_FILTERS: 32
QUEUE_SIZE: 10
