CASES_DIR: "./cases"
CASES_PREFIX: "/home/marsdenlab/datasets/vascular_data"

LEAK: 0.2
CROP_DIMS: 128
IMAGE_DIMS: 192
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
TRAIN_STEPS: 20000
PRINT_STEP: 20
INIT: 0.07
L2_REG: 0.001
NUM_FILTERS: 32
QUEUE_SIZE: 500
